<?php include dirname(__FILE__,2).'/header.phtml'; ?>
<div class="container">
    <section class="col-6">
        <h1>Créer un nouvel utilisateur</h1>
        <?php if(isset($error)): ?>
            <div class="alert alert-danger"><?= htmlspecialchars($error); ?></div>
        <?php endif; ?>
        <form method="post">
            <div class="form-group">
                <label for="firstname">Prénom</label>
                <input type="text" class="form-control" maxlength="60" value="<?= htmlspecialchars($user->firstname??'')?>" name="firstname" id="firstname"  aria-describedby="firstnameHelp" placeholder="Votre prénom" required>
            </div>
            <div class="form-group">
                <label for="lastname">Nom</label>
                <input type="text" class="form-control" maxlength="60" value="<?= htmlspecialchars($user->lastname??'')?>"name="lastname" id="lastname"  aria-describedby="lastnameHelp" placeholder="Votre nom" required>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Adresse E-mail</label>
                <input type="email" name="email" value="<?= htmlspecialchars($user->email??'')?>" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Votre adresse email" required>
            </div>
            <div class="form-group">
                <label for="password">Mot de passe</label>
                <input type="password" name="password" class="form-control" id="password" placeholder="Choisissez un mot de passe">
            </div>
            <?php $roles = json_decode($user->roles, true); ?>
            <div class="form-group">
                <div class="form-check">
                    <input type="checkbox" name="roles[]"<?= (in_array('user', $roles)?' checked="checked"':'') ?> value="user" class="form-check-input" id="role_user">
                    <label class="form-check-label" for="role_user">Utilisateur</label>
                </div>
                <div class="form-check">
                    <input type="checkbox" name="roles[]"<?= (in_array('marketing', $roles)?' checked="checked"':'') ?> value="marketing" class="form-check-input" id="role_marketing">
                    <label class="form-check-label" for="role_marketing">Marketing</label>
                </div>
                <div class="form-check">
                    <input type="checkbox" name="roles[]"<?= (in_array('webmaster', $roles)?' checked="checked"':'') ?> value="webmaster" class="form-check-input" id="role_webmasteur">
                    <label class="form-check-label" for="role_webmasteur">Webmasteur</label>
                </div>
                <div class="form-check">
                    <input type="checkbox" name="roles[]"<?= (in_array('admin', $roles)?' checked="checked"':'') ?> value="admin" class="form-check-input" id="role_admin">
                    <label class="form-check-label" for="role_admin">Administrateur</label>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">S'inscrire</button>
        </form> 
    </section>
</div>
<?php include dirname(__FILE__,2).'/footer.phtml'; ?>
