<?php include 'header.phtml'; ?>
<div class="container">
    <section class="col-6">
        <h1>Connexion</h1>
        <?php if(isset($error)): ?>
            <div class="alert alert-danger"><?= htmlspecialchars($error); ?></div>
        <?php endif; ?>
        <form method="post">
            <div class="form-group">
                <label for="exampleInputEmail1">Adresse E-mail</label>
                <input type="email" name="email" value="<?= $_POST['email']??''?>" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Votre adresse email" required>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Mot de passe</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Votre mot de passe" required>
            </div>
            <button type="submit" class="btn btn-primary">Se connecter</button>
        </form> 
    </section>
</div>
<?php include 'footer.phtml'; ?>
