<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon E-commerce</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">

            <a class="navbar-brand" href="/">E-commerce</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav">
                    <li class="nav-item<?= ROUTE == '/' ? ' active' : ''; ?>">
                        <a class="nav-link" href="/">Accueil</a>
                    </li>
                    <?php if(isset($_SESSION['user'])) : ?>
                    <li class="nav-item<?= ROUTE == '/deconnexion' ? ' active' : ''; ?>">
                        <a class="nav-link" href="/deconnexion">Déconnexion</a>
                    </li>
                    <?php else : ?>                  
                    <li class="nav-item<?= ROUTE == '/inscription' ? ' active' : ''; ?>">
                        <a class="nav-link" href="/inscription">Inscription</a>
                    </li>
                    <li class="nav-item<?= ROUTE == '/connexion' ? ' active' : ''; ?>">
                        <a class="nav-link" href="/connexion">Connexion</a>
                    </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </nav>

    <?php 
        if(isset($flash) && is_array($flash) && sizeof($flash) > 0) : 
            foreach ($flash as $type => $messages) : 
                foreach ($messages as $message) : 
    ?>
        <div class="container mt-4">
            <div class="alert alert-<?= $type == \Berlioz\FlashBag\FlashBag::TYPE_ERROR ? 'danger' : $type ; ?>">
                <?= $message; ?>
            </div>
        </div>
    <?php
                endforeach; 
            endforeach; 
        endif; 
    ?>

    <?php if(isset($_SESSION['user'])) : ?>
        <div class="container">
            Bienvenue <?= $_SESSION['user']->firstname; ?>
        </div>
    <?php endif; ?>