<?php include dirname(__FILE__,2).'/header.phtml'; ?>
<div class="container">
    <section class="col-6">
        <h1>Création d'un nouveau produit</h1>
        <?php if(isset($error)): ?>
            <div class="alert alert-danger"><?= htmlspecialchars($error); ?></div>
        <?php endif; ?>
        <form method="post">
            <div class="form-group">
                <label for="title">Désignation du produit</label>
                <input type="text" class="form-control" maxlength="160" value="<?= htmlspecialchars($_POST['title']??'')?>" name="title" id="title"  aria-describedby="firstnameHelp" placeholder="Désignation" required>
            </div>
            <div class="form-group">
                <label for="description">Description du produit</label>
                <textarea class="form-control" rows="4" name="description" id="description" aria-describedby="lastnameHelp" placeholder="Description" required><?= htmlspecialchars($_POST['description']??'')?></textarea>
            </div>
            <div class="form-group">
                <label for="price">Prix</label>
                <input type="number" step="0.01" min="0" name="price" value="<?= htmlspecialchars($_POST['price']??0)?>" class="form-control" id="price" aria-describedby="emailHelp" placeholder="Prix en €" required>
            </div>
            
            <button type="submit" class="btn btn-primary">Enregistrer</button>
        </form> 
    </section>
</div>
<?php include dirname(__FILE__,2).'/footer.phtml'; ?>
